export interface BeginnerLesson {
  id: string;
  title: string;
  minutes: number;
  goal: string;
  setup: string;
  concept: string;
  example: string;
  steps: string[];
  expected: string;
  troubleshoot: string;
  record: string;
  question: string;
  answer: string;
  aiPrompt: string;
  sources: Array<{ title: string; url: string }>;
}

// Authored beginner course. No network calls or executable lesson snippets.
export const beginnerCourse: BeginnerLesson[] = [
  {
    id: "beginner-01", title: "Start here: your tools and your first session", minutes: 20,
    goal: "Explain what each tool does and open a working local practice environment.",
    setup: "Windows, Docker Desktop, a browser, and this SurfaceTrace checkout. Coding experience is not required.",
    concept: "A web application is a program you use through a browser. The browser asks a server for information; the server replies. Your first job is to observe that conversation. DevTools is the browser's inspection window. Burp Suite is a separate tool that can record and resend requests. SurfaceTrace is your investigation notebook: it imports recorded traffic, organizes it, and helps compare evidence. GitLab GDK runs a separate copy of GitLab for development and optional local practice. GDK is not a scanner, and you do not need it to begin. An endpoint is one address and method an application accepts. An observation is one recorded exchange with it.",
    example: "Browser → local practice application\nDevTools or Burp → observe the conversation\nHAR file → SurfaceTrace → question, comparison, evidence\nGDK → optional application to investigate later",
    steps: [
      "Open Docker Desktop. Wait until its engine is running. In PowerShell, enter: cd C:\\Users\\SuperAdmin\\.vscode\\SurfaceTrace",
      "Enter: docker compose up -d --wait. This starts your local services. Leave your GitLab/GDK setup alone for now.",
      "Open http://127.0.0.1:5173 in your browser. 127.0.0.1 means this computer; 5173 selects this application's port, rather like a particular door.",
      "In another tab open http://127.0.0.1:5173/api/health. Look for ok: true. Return here and read the next lesson before importing anything.",
      "To stop at the end of a session, run docker compose stop in the same folder. Do not delete volumes: they contain your Docker investigation data.",
    ],
    expected: "The application opens and API health reports success. You can explain why the browser, traffic inspector, notebook, and target application are different things.",
    troubleshoot: "Connection refused means the service is not reachable. Run docker compose ps and docker compose logs --tail 30. Do not start npm run win:dev while Docker owns port 5173. Native Windows is an alternative mode, not another required service; it has a separate local database.",
    record: "Write the folder, startup command, app URL, and one sentence describing each tool. This is your recovery note for the next session.",
    question: "Do you need to start GDK before opening SurfaceTrace? Which tool creates the practice application?",
    answer: "No. SurfaceTrace includes a tiny local lab and sample traffic. GDK creates a separate GitLab environment for later exercises. SurfaceTrace neither installs GitLab nor automatically captures its traffic.",
    aiPrompt: "Act as my patient tutor. Explain browser, server, port, DevTools, Burp, and SurfaceTrace using this local setup. Ask me one question at a time. Do not run commands or assume I understand programming.",
    sources: [],
  },
  {
    id: "beginner-02", title: "Decide what you are allowed to test", minutes: 20,
    goal: "Write a small test plan before sending a request.",
    setup: "Use the built-in local lab only: http://127.0.0.1:5173/lab/projects/100 and /200.",
    concept: "Security testing asks whether a rule is enforced, not whether a page looks unusual. A scope states which systems, accounts, actions, and times you may test. Being able to open a website does not grant testing permission. Passive work means studying traffic already recorded. Active work sends a new request and may change state. Even a GET request can have effects in a poorly designed application. A baseline is the unmodified exchange you compare against. A hypothesis is a question, not a conclusion. Here the lab's records are invented and public; their owner labels do not implement access control.",
    example: "Target: my local SurfaceTrace lab\nAllowed: GET /lab/projects/100 and /lab/projects/200\nQuestion: which response fields change when I change the ID?\nLimit: one baseline and one comparison; no scanning\nStop: unexpected host, personal data, or uncertain behavior",
    steps: [
      "Copy the example into a private notebook. Replace nothing yet; this is the exact scope for the first exercise.",
      "Write your expected result: both example records are publicly readable and their id, name, and owner fields differ.",
      "Separate fact from inference: 'the body contains an owner field' is a fact; 'only that owner may read it' needs a policy that this simple lab does not have.",
      "Before each later exercise, name the target, identity, one change, request limit, and stop condition aloud. For someone else's service obtain its actual written rules first.",
    ],
    expected: "A five-line plan tells you what to do and when to stop. An invented lab record is not mistaken for a real authorization vulnerability.",
    troubleshoot: "If an exercise leads to another host or a real account, pause and return to the local URLs. Do not expand scope just because AI suggests an interesting endpoint.",
    record: "Save scope, expected behavior, baseline, one variable, and stopping rule. Use an observation ID or timestamp to connect later results to this plan.",
    question: "You receive 200 for both records. Is that proof of broken access control?",
    answer: "No. This lab intentionally publishes both. A security finding needs an expected rule and evidence that the application violates it; a status code alone supplies neither.",
    aiPrompt: "Review my five-line local test plan. Identify missing assumptions and ambiguous permissions. Ask for clarification; do not add targets, payloads, scans, or additional requests.",
    sources: [],
  },
  {
    id: "beginner-03", title: "DevTools: watch one browser request", minutes: 25,
    goal: "Find the exact request caused by opening a page.",
    setup: "Chrome or Edge and the local lab. Keep this lesson in a separate tab.",
    concept: "One page can cause many requests: the document, scripts, images, and background API calls. The Network panel is a list of those exchanges, not a list of vulnerabilities. Opening an API address directly usually produces a document request; it does not necessarily appear under Fetch/XHR. The request name can be just its final path segment. Always check the full URL before deciding what a row represents.",
    example: "Address: http://127.0.0.1:5173/lab/projects/100\nExpected request: GET /lab/projects/100\nExpected response body: {\"id\":100,\"name\":\"Alpha\",\"owner\":\"Account A\"}",
    steps: [
      "Open the lab URL in a new tab. Press F12 or Ctrl+Shift+I, then choose Network. Use the panel overflow menu if Network is hidden.",
      "Select All, clear the text filter, and confirm recording is enabled. Clear the request list, then reload this tab once.",
      "Select the row for 100. In Headers, find Request URL, Request Method, and Status Code. The favicon row, if present, is unrelated.",
      "Open Response to see the actual returned text. Preview can format the same data more readably. Compare the body with the example.",
      "Write what browser action caused this request. Do not resend anything yet; observing one normal page load is enough.",
    ],
    expected: "You identify the GET and its JSON response without confusing it with a script or favicon. JSON is a structured text format; the next lessons teach you to read it.",
    troubleshoot: "An empty list often means DevTools opened after the request, recording is off, or a filter hides documents. Reload with All selected. A 502 from the UI proxy suggests the API/lab is still starting; check Docker health first.",
    record: "Record action, URL, method, status, and the three response field names. Do not record authentication values from unrelated tabs.",
    question: "Why might Fetch/XHR hide the request when you type this API URL into the address bar?",
    answer: "Direct navigation is normally a document request. Fetch/XHR limits the display to script-driven requests; the filter is a view, not a statement that other traffic did not occur.",
    aiPrompt: "I opened this local URL and captured these non-secret fields. Help me identify which row is my page request. Explain each field, then ask me to locate it myself.",
    sources: [{ title: "Chrome: inspect network activity", url: "https://developer.chrome.com/docs/devtools/network" }],
  },
  {
    id: "beginner-04", title: "Read a URL and find the input", minutes: 20,
    goal: "Separate destination from the data a request carries.",
    setup: "The request from lesson 3 and a notebook; the longer URL below is an illustration, not a new target.",
    concept: "A URL is an address. Its scheme says how to connect; host and optional port identify the destination; path identifies a resource; a query carries named values. A fragment after # is normally handled in the browser and is not included in an HTTP request target. An ID is a label for an object, not a permission check. An endpoint template such as /projects/{id} groups many object addresses into one pattern. Encoding such as %20 represents a space; it is not encryption. Different spellings or decoding rules can matter, so keep the captured original as your reference.",
    example: "http://127.0.0.1:5173/lab/projects/100?view=summary#details\nscheme: http | host: 127.0.0.1 | port: 5173\npath: /lab/projects/100 | query: view=summary\nfragment: details (not sent as part of the request target)",
    steps: [
      "Label each part of the illustration. Circle the object ID 100 and the query name view. They are different input locations.",
      "Return to the captured real request. Confirm its URL has no query. Do not add the illustrative query: the tiny lab matches exact paths and may return 404.",
      "Write the template /lab/projects/{id}. Explain that /100 and /200 can be two observations of one endpoint.",
      "Compare a path ID with a hostname. Changing 100 to 200 stays on this lab; changing the hostname would change the target and requires a new scope decision.",
    ],
    expected: "You can point to the intended input without changing the server, port, or request method accidentally.",
    troubleshoot: "If the address contains ?, split on that first, then split query pairs on &. A value may itself contain encoded punctuation. Do not decode and resend unfamiliar strings just to see what happens.",
    record: "Make two columns: location and name. Enter path/id and, for the illustration only, query/view. Values are observations, not proof of vulnerability.",
    question: "Does a predictable number in a path prove that another account can access the object?",
    answer: "No. Predictability identifies an input worth understanding. The server may enforce ownership correctly. You need an access policy and a controlled account comparison.",
    aiPrompt: "Break this synthetic URL into scheme, host, port, path, query, and fragment. Ask me which single value I intend to compare. Do not suggest other hosts or enumerate IDs.",
    sources: [],
  },
  {
    id: "beginner-05", title: "Read requests and responses without coding", minutes: 25,
    goal: "Explain the method, headers, body, and status of one exchange.",
    setup: "Keep the local request open in DevTools Network.",
    concept: "A request asks the server to do something; a response says what happened. Headers are named metadata, such as the format accepted or returned. A body is the main content and can be absent. HTTP/2 and HTTP/3 displays may use pseudo-headers instead of an HTTP/1.1-style first line; you are still finding the method and target. A 2xx status usually signals success, 3xx a redirect, 4xx a request/access issue, and 5xx a server failure. The body may still contain a login page or an application-level error even when the status is 200. Read all three: status, relevant headers, and body.",
    example: "GET /lab/projects/100 HTTP/1.1\nHost: 127.0.0.1:5173\n\nHTTP/1.1 200 OK\nContent-Type: application/json\n\n{\"id\":100,\"name\":\"Alpha\",\"owner\":\"Account A\"}",
    steps: [
      "Identify the request method and target in Headers. There is no request JSON body for this GET; the JSON you see in Response came from the server.",
      "Find the response Content-Type. application/json tells you how to interpret the returned body; it does not tell you whether the contents are authorized.",
      "Read the actual three fields. Write 'received project 100' rather than only 'got 200'.",
      "Use the example to label which lines belong to the request and which to the response. Notice that Cookie, when present, is a request header; Set-Cookie is a response header.",
    ],
    expected: "Your observation includes a meaningful description of returned content and does not confuse a response body with an input you sent.",
    troubleshoot: "If Preview shows a webpage, inspect Response and Content-Type. A login page is not the protected object you expected. Record redirects separately rather than silently assuming the final page was the first response.",
    record: "Method, path, status, Content-Type, short body summary, and any redirect destination. Remove secret header values before sharing.",
    question: "Two responses are both 200. What must you inspect before calling them equivalent?",
    answer: "Compare their headers and meaningful body fields. One might be a login page, a different record, or an error envelope. Also check whether identity and other request inputs stayed constant.",
    aiPrompt: "Using this redacted request and response, label the two directions. Explain status, Content-Type, and body in ordinary language. Separate observed facts from possible interpretations.",
    sources: [],
  },
  {
    id: "beginner-06", title: "Methods and input locations: choose what to inspect", minutes: 25,
    goal: "Make a small inventory of user-controlled inputs and their possible effects.",
    setup: "Use the examples below or fixtures/starter-hars/02-input-surfaces.har. Do not send the illustrative state-changing requests.",
    concept: "GET generally reads, POST commonly submits or creates, PUT replaces a representation, PATCH updates part of it, and DELETE removes it. Method names are conventions, not guarantees of safety. Inputs can be in a path, query, header, cookie, form body, or JSON body. Your question depends on the input's job: an object ID raises ownership questions; a return URL raises destination questions; a price raises server-side calculation questions. A long list of inputs is a map for choosing one question, not instructions to attack everything.",
    example: "GET /projects/100?view=summary\nPATCH /profile with {\"displayName\":\"Learner\"}\nCookie: session=[REDACTED]\nInput map: path/id; query/view; body-json/displayName; cookie/session",
    steps: [
      "For each example, label read versus potential state change. Mark PATCH as something that requires a disposable record and explicit authorization before replay.",
      "List input names, locations, and likely purposes. Do not copy cookie values. A header you did not type may still come from the browser or a proxy.",
      "Choose one harmless learning question: does changing the local lab's path ID select a different record? Leave method, host, and other inputs fixed.",
      "For a future real test, add 'expected server rule' beside the input. If you cannot state it, learn the normal workflow before designing a mutation.",
    ],
    expected: "You have a small input map with a reason for each item and one chosen question. Nothing is sent merely because an input exists.",
    troubleshoot: "No Payload tab often means no request body. URL-encoded forms and JSON are different formats; changing Content-Type without changing the body can create an irrelevant parsing error.",
    record: "Location, input name, observed type, purpose, possible state change, and the rule you want to understand. Separate synthetic examples from captured evidence.",
    question: "Why is changing both an ID and the request method a poor first comparison?",
    answer: "You changed two dimensions. A response difference might be caused by the method rather than the ID. Keep a baseline and change only the value relevant to your question.",
    aiPrompt: "Help me make an input inventory from these redacted fields. For each, explain its possible purpose and one question to ask. Do not generate payload lists or execute requests.",
    sources: [],
  },
  {
    id: "beginner-07", title: "Read JSON: objects, lists, and field paths", minutes: 25,
    goal: "Describe structured data accurately without writing a program.",
    setup: "A notebook and the synthetic JSON below. No Console commands are needed.",
    concept: "JSON is text with a small grammar. Braces hold an object: named fields paired with values. Square brackets hold a list, called an array. Text uses double quotes; numbers do not. true and false are booleans. null explicitly means an empty or absent value, which differs from a missing field. A field path is a way to name a nested location. Learning to read paths lets you explain exactly which part changed in a response instead of saying 'the page looked different'.",
    example: "{\n  \"project\": {\"id\": 100, \"public\": false},\n  \"members\": [{\"role\": \"guest\"}],\n  \"description\": null\n}\nPaths: project.id, project.public, members[0].role, description",
    steps: [
      "Circle the top-level names project, members, and description. Underline the nested names id, public, and role.",
      "Write the type of every value: object, array, number, boolean, string, or null. The first array position is numbered zero in common programming notation.",
      "Compare a second copy where only project.id is 200. Write the exact path and before/after values.",
      "Compare description: null with no description field at all. They are different observations, but neither automatically indicates a security problem.",
      "Return to the live lab response and identify its three top-level fields. The lab uses simpler data than the teaching illustration.",
    ],
    expected: "You can say 'project.id changed from number 100 to number 200' and explain why a string \"100\" would be a different type.",
    troubleshoot: "Single quotes, comments, or a comma after the final field make a document invalid JSON. If a response is HTML, do not force it into a JSON interpretation. Formatting and field ordering alone may not change meaning.",
    record: "Use field path | old type/value | new type/value | meaning still unknown. Replace personal values with consistent labels before giving this table to AI.",
    question: "In members[0].role, what do the zero and role each refer to?",
    answer: "Zero selects the first item in the members array. role selects a field inside that item. Neither is a command or a permission grant.",
    aiPrompt: "Teach me to read this synthetic JSON. Ask me to identify objects, arrays, and one field path. Then give feedback. Do not write a script until I can explain the data manually.",
    sources: [],
  },
  {
    id: "beginner-08", title: "DevTools: capture a useful HAR safely", minutes: 30,
    goal: "Create a small traffic recording that you can explain and import.",
    setup: "Use only the local lab in a dedicated browser tab. A HAR is a file containing recorded HTTP exchanges.",
    concept: "Good evidence captures one understandable action. A giant recording of unrelated tabs makes it difficult to tell which request caused what. A sanitized HAR export omits some sensitive headers, but it can still contain private paths, query values, bodies, or response data. SurfaceTrace also redacts recognized patterns; neither layer guarantees that every secret is removed. For this exercise, the fixed Alpha and Beta records contain invented data. Keep captures local until you have reviewed them.",
    example: "Capture plan:\n1. Open project 100\n2. Open project 200\n3. Export two relevant requests\nFile: local-project-comparison.har\nDo not include unrelated accounts or tabs.",
    steps: [
      "Open DevTools Network before recording. Select All and clear the list. Enable Preserve log so navigating to the second URL retains the first exchange.",
      "Visit http://127.0.0.1:5173/lab/projects/100, then change only the final number to 200 in the address bar.",
      "Check that both project responses are present and contain their expected JSON bodies. Ignore favicon traffic; use the filter projects if helpful.",
      "Use Export HAR (sanitized), or the request-list context menu's sanitized HAR option. Browser labels vary; avoid the option that explicitly includes sensitive data.",
      "Save the file in a private local folder. Open it as text and search for known personal email addresses or tokens if you captured anything beyond this toy lab. Never paste a real session value into AI.",
      "Turn Preserve log off after this exercise so the next capture does not silently accumulate unrelated navigation.",
    ],
    expected: "A .har file contains the two lab exchanges and their bodies. You can describe what was captured, when, and why.",
    troubleshoot: "Missing requests: open Network before the action and enable recording. Missing first navigation: use Preserve log. An export can include more rows than expected depending on the chosen option; inspect the file instead of assuming the filter removed them.",
    record: "File name, capture time, local target, actions performed, two expected IDs, and a note that data is synthetic. Preserve the original capture privately and use redacted copies for discussion.",
    question: "Does 'sanitized HAR' mean every secret in a response body is gone?",
    answer: "No. It is not a universal content scrubber. Restrict what you record, inspect the result, and remove sensitive content before sharing or uploading it.",
    aiPrompt: "Give me a checklist to inspect my HAR without uploading it. Tell me which categories may contain secrets. Use synthetic examples and do not ask for cookie, token, or password values.",
    sources: [{ title: "Chrome: HAR export and Network controls", url: "https://developer.chrome.com/docs/devtools/network/reference" }],
  },
  {
    id: "beginner-09", title: "SurfaceTrace: turn a capture into a notebook", minutes: 35,
    goal: "Find an endpoint, distinguish evidence from a suggestion, and preserve your working context.",
    setup: "SurfaceTrace and the previous HAR, or fixtures/sample.har if capture is not ready. Use this installation for disposable learning data; the current UI has no project switcher.",
    concept: "An observation is one recorded request/response. An endpoint groups similar observations, often replacing changing IDs with a template. A hypothesis is a suggested question inferred from traffic; it does not prove a flaw. Identity labels and notes are your own annotations. Importing a new HAR replaces the project's active import, so do not overwrite an investigation casually. The notebook preserves structured context; it is not a live connection to Burp, DevTools, or GDK.",
    example: "Observation A: GET /lab/projects/100 → Alpha\nObservation B: GET /lab/projects/200 → Beta\nEndpoint: GET /lab/projects/{id}\nQuestion: Which fields changed?\nConclusion so far: two different public lab records",
    steps: [
      "Open Command Center. This UI uses the active server project and has no project picker. Keep earlier captures and important notes separately before replacing an import; use the learning installation only for these exercises.",
      "Choose IMPORT AUTHORIZED HAR and select your local recording. Read the import result. Do not assume a successful import proves the source was trustworthy.",
      "Open Investigation, select the project endpoint, and choose each observation in the HTTP inspector. Locate request target, response body, and parsed inputs.",
      "Read a generated question. Label it 'needs investigation', not 'confirmed'. If an ID triggers an authorization question, remember this toy lab intentionally allows both objects.",
      "In your own notebook, write a short note linking the endpoint to your capture plan. Open Evidence and distinguish observations from comparisons and conclusions.",
    ],
    expected: "You can navigate from a grouped endpoint back to the underlying exchanges and explain what the application inferred versus what you actually observed.",
    troubleshoot: "No useful requests: verify the HAR has log.entries and response content. Missing body may be a capture limitation or redaction. Do not invent the missing content. If important investigation data is already loaded, preserve it before importing again.",
    record: "Project name, source file, endpoint template, observation identifiers, missing data, and one open question. Keep raw secrets out of free-text notes, too.",
    question: "Does labeling an observation Account A change the request's actual credentials?",
    answer: "No. It annotates the evidence. It cannot establish which identity really sent a captured request or log in on your behalf. Identity must be confirmed at capture time.",
    aiPrompt: "Here are my redacted observations and the app's generated question. Tell me which statements are facts, annotations, and hypotheses. Help me write one next question without claiming a vulnerability.",
    sources: [],
  },
  {
    id: "beginner-10", title: "DevTools: cookies, sessions, and browser storage", minutes: 30,
    goal: "Recognize identity context without copying or confusing credentials.",
    setup: "Use a local test account in GDK when it is ready, or study the synthetic example. The tiny project lab does not have login sessions.",
    concept: "A cookie is a value the browser stores and may send with matching requests. A session lets the server connect separate requests to an identity or state. The cookie is like a claim ticket, not necessarily a readable username. Local Storage and Session Storage are browser key/value stores; their entries are not automatically sent as Cookie headers, though scripts may use them in requests. HttpOnly restricts JavaScript access to a cookie; Secure concerns HTTPS transmission; SameSite influences cross-site sending. These attributes have specific jobs and are not blanket proof that a login system is safe.",
    example: "Response: Set-Cookie: session=[REDACTED]; HttpOnly; SameSite=Lax\nLater request: Cookie: session=[REDACTED]\nNotes should contain: cookie name and attributes, never the live value.",
    steps: [
      "In a dedicated local test browser profile, open DevTools → Application → Cookies and select the local origin. Inspect names and attributes only.",
      "Open Network and compare a normal logged-in request with the login page in a separate anonymous profile. Confirm the visible username before assigning identity labels.",
      "Inspect Local Storage and Session Storage separately. Record key names and apparent purpose, not values. Do not delete storage in your normal browsing profile.",
      "Sign out of the disposable test account through the app's normal UI. Observe the next request and displayed login state. This is an observation, not a complete session-security audit.",
    ],
    expected: "You can explain how an account's browser state affects requests and why two tabs in the same profile may share a login.",
    troubleshoot: "No cookies in the simple lab is normal. HttpOnly cookies need not appear in document.cookie. Do not paste unknown Console code to reveal or copy credentials; DevTools itself is sufficient for this inspection.",
    record: "Identity label, how you confirmed it, cookie names/attributes, browser profile, and whether you were logged in at capture time. Keep Account A and Account B captures distinct.",
    question: "Are two ordinary tabs a reliable way to keep two different account sessions separate?",
    answer: "Usually not: tabs in one profile share relevant cookies and storage. Use separate dedicated profiles or isolated sessions and verify the active username before each capture.",
    aiPrompt: "Explain the difference between a cookie, a session, Local Storage, and Session Storage. Use redacted examples. Help me plan separate local test identities without exposing their credentials.",
    sources: [{ title: "Chrome: inspect cookie attributes", url: "https://developer.chrome.com/docs/devtools/application/cookies" }],
  },
  {
    id: "beginner-11", title: "Authentication and authorization: write the rule first", minutes: 30,
    goal: "Build a tiny role-and-object access table before interpreting a response.",
    setup: "Paper exercise first. Later use only accounts and objects you created in your local GitLab.",
    concept: "Authentication asks who is making a request. Authorization asks whether that identity may perform this action on this object. Horizontal access concerns another person's object at a similar role; vertical access concerns an action reserved for a more privileged role. A hidden button is a user-interface choice, not a server-side access check. You need to know object visibility, group membership, role, and the intended policy. A public project is a poor example of data that should be private. 'Admin can do it' does not tell you whether a normal member should be able to.",
    example: "Illustrative policy, not GitLab's universal role rules:\nPrivate object A: A may read; unrelated B may not; anonymous may not\nPublic object P: A, B, and anonymous may read\nDeletion: only the explicitly authorized owner/admin",
    steps: [
      "Write one object and one action in a table. Fill in the expected result for Account A, unrelated Account B, and Anonymous.",
      "Write where that rule comes from: a documented policy, a local setup you controlled, or an assumption needing confirmation.",
      "Mark public versus private visibility explicitly. Roles in GitLab depend on project membership and feature; do not guess from role names.",
      "Plan a comparison that holds the object constant and changes only identity. Verify the sessions separately before any real capture.",
      "For the simple Alpha/Beta lab write 'no authentication or private-object policy'. Do not classify its successful responses as a bypass.",
    ],
    expected: "You have a policy table and understand why ownership-looking fields alone cannot establish a security boundary.",
    troubleshoot: "Different results may come from a wrong session, changed object, public visibility, expired login, cache, or a redirect. Check those explanations before making a finding.",
    record: "Object, visibility, role/membership, expected action, actual response, identity evidence, and remaining uncertainty. A blank expected-policy cell means more setup is needed.",
    question: "Why is a missing Delete button insufficient evidence that deletion is forbidden?",
    answer: "The interface can hide controls, but only the server can enforce the action's authorization reliably. Establish policy first; any active check must use disposable local data and explicit permission.",
    aiPrompt: "Review my access table. Identify which entries are assumptions and which have evidence. Ask me about visibility, membership, and identity before suggesting any test.",
    sources: [{ title: "PortSwigger: access-control concepts", url: "https://portswigger.net/web-security/access-control" }],
  },
  {
    id: "beginner-12", title: "Burp Suite: connect the built-in browser", minutes: 25,
    goal: "Capture local traffic in Burp without changing system proxy settings.",
    setup: "Burp Suite Community or Professional on Windows, plus the running SurfaceTrace lab. Scanner features are not needed.",
    concept: "A proxy sits between a client and a server. Burp's browser is configured to send its traffic through Burp. Proxy Intercept can pause an exchange before it continues; HTTP history records traffic even when interception is off. A page that appears stuck may simply be waiting for you to forward a paused request. Start with interception off so you can learn the normal traffic pattern. Use Burp's browser for these exercises, not a browser containing your personal accounts.",
    example: "Burp browser → Burp Proxy → http://127.0.0.1:5173/lab/projects/100\nIntercept OFF: normal browsing continues\nIntercept ON: a matching request can wait for Forward or Drop",
    steps: [
      "Launch Burp. If asked about a project, a temporary project is sufficient for this exercise; retain your notes separately because temporary sessions are not durable evidence storage.",
      "Go to Proxy → Intercept. Set Intercept off and choose Open browser. Use that browser for the next action.",
      "Open the exact local project-100 URL. Return to Burp → Proxy → HTTP history and locate its host, path, and GET method.",
      "Select the row and compare Request and Response with DevTools. You are observing the same kind of HTTP exchange through another tool.",
      "Optionally enable Intercept for one fresh local request, inspect it, then Forward once. Return Intercept to off before continuing.",
    ],
    expected: "The page loads in Burp's browser and its exchange appears in HTTP history. You know why a paused request does not mean the server is broken.",
    troubleshoot: "No history: confirm you used Burp's browser and check display filters. A stuck page: inspect the Intercept tab. Do not disable browser certificate checks or sandbox protections to solve a first-session setup problem; the local HTTP lab does not need a custom CA installation.",
    record: "Burp edition, target URL, whether Intercept was on/off, and the history row's method/status. Do not save unrelated browsing traffic.",
    question: "Does turning Intercept off disable HTTP history?",
    answer: "No. Interception controls pausing. History can still record the browser's proxied traffic, which is the simplest mode for this lesson.",
    aiPrompt: "Walk me through Burp's built-in browser and HTTP history for my local lab, one click at a time. If the page hangs, ask whether Intercept is on before proposing network changes.",
    sources: [{ title: "PortSwigger: Burp's browser", url: "https://portswigger.net/burp/documentation/desktop/tools/burps-browser" }, { title: "PortSwigger: intercepting traffic", url: "https://portswigger.net/burp/documentation/desktop/getting-started/intercepting-http-traffic" }],
  },
  {
    id: "beginner-13", title: "Burp: use history and scope to find the right exchange", minutes: 25,
    goal: "Locate a meaningful request and avoid confusing a display filter with permission.",
    setup: "The local project request captured in Burp. Keep Intercept off.",
    concept: "HTTP history is a record of traffic sent through Burp. Scope identifies the target set you intend to work on; filters make the displayed list easier to read. Neither a filter nor a scope label supplies legal authorization. They also are not a universal firewall preventing all other traffic. History can contain unrelated browser activity, so identify the exact protocol, host, port, method, and path. A useful first map follows normal application actions: sign in, view a project, view its settings. Do not replace that map with a directory scan.",
    example: "Our exercise target: http + 127.0.0.1 + port 5173 + /lab/projects/\nRelevant row: GET /lab/projects/100 → 200\nUnrelated row: a browser background service on another host",
    steps: [
      "In HTTP history, find the known /lab/projects/100 request. Inspect the full destination; 127.0.0.1:3000 would be your separate GitLab, not this lab.",
      "Use the selected target's context menu to add it to scope. Inspect Target → Scope and narrow it to the intended local protocol/host/port and relevant path as your version permits.",
      "Use the history filter to show in-scope traffic. Confirm the known request remains visible. The filter changes the display; verify the target again before sending anything.",
      "Select Request and Response. Annotate the row with a short description such as 'baseline, public local project 100'. Record normal behavior before looking for anomalies.",
      "For later GitLab practice make a separate scope entry and separate notes. Never silently treat every localhost port as the same authorized application.",
    ],
    expected: "You can find the exchange again and explain which normal browser action produced it. Your scope and notes identify one local application precisely.",
    troubleshoot: "If a row disappears, clear display filters and re-check the target definition. Do not alter the request to make it fit an incorrect scope entry. Browser extensions can generate background traffic unrelated to the lesson.",
    record: "Exact target, scope choices, history annotation, baseline status/body summary, and any missing context. Avoid copying the entire history into a public report.",
    question: "Does 'show only in-scope' stop the browser from making any out-of-scope requests?",
    answer: "It is a display filter. Treat scope and filters as organization aids; check the destination and authorization yourself before each deliberate test.",
    aiPrompt: "Help me identify one meaningful row from these redacted history fields. Ask for the host, port, method, path, and user action. Explain any scope ambiguity before discussing mutations.",
    sources: [{ title: "PortSwigger: HTTP history", url: "https://portswigger.net/burp/documentation/desktop/tools/proxy/http-history" }, { title: "PortSwigger: target scope", url: "https://portswigger.net/burp/documentation/desktop/getting-started/setting-target-scope" }],
  },
  {
    id: "beginner-14", title: "Burp Repeater: send one controlled comparison", minutes: 30,
    goal: "Replay a baseline once, change only an ID, and explain the outcome.",
    setup: "Use only the fixed local GET /lab/projects/100 and /200 routes. Both are public synthetic records.",
    concept: "Repeater is a manual request editor and sender. Unlike viewing an old history row, pressing Send makes a new network request. First resend the unmodified baseline so you know the original still behaves as expected. Then alter one value and compare the actual response. Keep the target host/port, method, headers, and identity constant. This lab is about learning controlled comparisons; it contains no login or authorization check to bypass.",
    example: "Baseline target: GET /lab/projects/100\nOnly changed target: GET /lab/projects/200\nExpected: id 100→200, name Alpha→Beta, owner Account A→Account B\nConclusion: changed record, not confirmed IDOR",
    steps: [
      "From Proxy HTTP history, right-click the known lab request and choose Send to Repeater. Open its Repeater tab and inspect the destination before sending.",
      "Send the unchanged GET once. Check for the Alpha response. If it differs from the captured baseline, stop and resolve the difference before editing.",
      "Duplicate the tab or keep the baseline result in your notes. Change only the final path segment from 100 to 200. Do not change the Host header, method, or port.",
      "Press Send once. Compare status, Content-Type, and JSON fields. Record the three expected field changes and the unchanged method/destination.",
      "Stop here. Do not iterate other IDs or use Intruder. You have already answered the learning question with two controlled requests.",
    ],
    expected: "Both responses are 200, and their three body fields differ. You can trace the result to one deliberate request change.",
    troubleshoot: "404: check the exact path and remove accidental query strings. Connection error: check Docker health and Repeater's destination. If redirects appear in a later exercise, inspect each destination explicitly rather than following it into a new target.",
    record: "Baseline request, comparison request, exact changed value, both responses, interpretation, and the statement that the lab is intentionally public. Never use a successful Send as a vulnerability verdict.",
    question: "Why send the unchanged baseline before your edited request?",
    answer: "It checks that the captured request still works in the current environment. Otherwise an expired session, changed server state, or wrong destination could be mistaken for the effect of your edit.",
    aiPrompt: "Compare these two synthetic Repeater exchanges. Verify that only the path ID changed. List observations separately from conclusions and challenge any claim that this public lab demonstrates an authorization bug.",
    sources: [{ title: "PortSwigger: Repeater walkthrough", url: "https://portswigger.net/burp/documentation/desktop/getting-started/reissuing-http-requests" }],
  },
  {
    id: "beginner-15", title: "Compare evidence in SurfaceTrace", minutes: 35,
    goal: "Create a passive comparison and explain the limits of a diff.",
    setup: "The active import containing both local project observations. If needed use fixtures/sample.har and adapt the IDs to what it actually contains.",
    concept: "A passive comparison analyzes stored traffic and sends no request. An active replay sends a new request and requires a separate approval path. A diff is a description of differences, not their security meaning. JSON field ordering or timestamps may differ for ordinary reasons. Redacted or truncated content limits what can be concluded. SurfaceTrace checks one mutation category, but you still need to inspect the captured requests: selecting one category does not prove that every other input or identity stayed constant.",
    example: "Question: what changes when the path ID changes?\nKnown baseline: project 100 observation\nChanged input: path ID\nKnown value: 100 | test value: 200\nResult: different public record\nUncertainty: this lab has no access policy to test",
    steps: [
      "Open Investigation and the grouped project endpoint. Inspect both stored requests first. Confirm host, method, and relevant headers match.",
      "Scroll to CONTROLLED COMPARISON (Change one variable), below the active-request panel. In CHOOSE HYPOTHESIS, select the object-access question as a learning question. Set Baseline observation to project 100, Changed input to path: id, Baseline value to 100, Changed value to 200, and Result observation to project 200.",
      "In Evidence note, write: I expect two public records with different id, name, and owner fields; this lab has no private-object rule. Click COMPARE + SAVE EVIDENCE. This compares stored exchanges. Do not use PREVIEW ACTIVE REQUEST or SEND THIS REQUEST for this exercise. Read status, headers, and body differences together.",
      "In the experiment notebook, open the saved comparison and use Tester conclusion and the structured explanation fields. Describe only what changed, what stayed constant, and the lack of an access-control rule. If content or identity evidence is missing, explain that limitation rather than labeling a finding.",
      "Open Evidence to locate the comparison record. Its hash supports integrity of the stored chain, not proof that your interpretation is correct or your original capture was authentic.",
    ],
    expected: "A saved comparison connects a baseline, one declared change, a result, and an honest conclusion. No request was sent by the passive step.",
    troubleshoot: "If the selected input does not exist, inspect the actual captured endpoint instead of following sample labels blindly. If multiple dimensions changed, capture a cleaner pair; do not force an unclear pair into a one-variable claim.",
    record: "Experiment question, baseline/comparison IDs, declared input, constants checked, material differences, and limitations. Repeater output is not automatically imported into SurfaceTrace; retain redacted Burp notes separately or capture the browser workflow as HAR.",
    question: "Does a verified evidence hash prove that a security finding is true?",
    answer: "No. It detects changes to the recorded material within the implemented chain. It cannot establish that the capture, identity assignment, policy assumption, or human conclusion was correct.",
    aiPrompt: "Review my experiment card. Check causal confounders, identity assumptions, redaction, and missing content. Help me write a conclusion proportional to the evidence, not a dramatic finding title.",
    sources: [],
  },
  {
    id: "beginner-16", title: "Recognize an access-control question", minutes: 35,
    goal: "Distinguish an interesting object ID from evidence of IDOR/BOLA.",
    setup: "Use fixtures/starter-hars/01-access-control.har for passive study. Active practice belongs only in a purpose-built authorized lab or your own carefully configured GitLab.",
    concept: "IDOR means insecure direct object reference; BOLA means broken object-level authorization. Both describe cases where an application fails to enforce whether this caller may access this object. The object may be named in a URL, query, or body. The name is not the flaw: the missing permission check is. To reason well, you need two known identities, ownership or membership facts, visibility, and the action being attempted. A 403 is evidence about one request, not a proof that every route is secure. A 200 may be intentionally public data.",
    example: "Controlled policy: A owns private object A; unrelated B has no access.\nComparison 1: keep object A fixed, change only A→B identity.\nAlternative comparison 2: keep A identity fixed, compare its object with a known private B object.\nDo not change both identity and object in the same comparison.",
    steps: [
      "Import the synthetic access-control fixture into the learning installation after preserving any previous work. Read its entries and identity hints; they are training labels, not evidence about a real account.",
      "Choose one response pair and write the intended policy. Identify whether the pair changes identity, object, or more than one thing.",
      "Compare returned content as well as status. A response that exposes a private field could matter even if the page also displays an error.",
      "List alternate explanations: public visibility, group membership, stale login, wrong cookie, cache, or a login-page response. Mark which you can rule out from the fixture and which you cannot.",
      "Write a bounded conclusion and the additional evidence you would need in a real authorized environment. Do not enumerate IDs to compensate for missing context.",
    ],
    expected: "You can explain the permission boundary and design a meaningful comparison without calling every numeric ID a vulnerability.",
    troubleshoot: "If the capture cannot prove the user's identity or the object's visibility, keep the conclusion provisional. Changing a label in SurfaceTrace cannot repair missing capture context.",
    record: "Expected policy, identity verification, object ownership/visibility, exact request difference, actual returned data, and what remains uncertain.",
    question: "Account B can read object A, but object A is public. What does that demonstrate?",
    answer: "It demonstrates public readability, which may be correct. Without a rule forbidding B's access, you have not demonstrated broken object-level authorization.",
    aiPrompt: "Act as a skeptical reviewer of this local access-control comparison. Ask about identity, visibility, and policy. Suggest the smallest missing piece of evidence, not more IDs to try.",
    sources: [{ title: "PortSwigger: object-level access control", url: "https://portswigger.net/web-security/access-control" }],
  },
  {
    id: "beginner-17", title: "DevTools: read HTML and JavaScript clues", minutes: 35,
    goal: "Use Elements and Sources to understand normal behavior without mistaking client code for server authority.",
    setup: "Use your local SurfaceTrace page. This lesson is read-only; no Console snippets are required.",
    concept: "HTML describes page structure. The DOM is the browser's current tree of elements, which JavaScript can change after loading. JavaScript runs behavior such as responding to a click or requesting data with fetch. JSON is a data format, not the same thing as a JavaScript program. Minified code is compressed for delivery, and source maps may make it easier to read when available. An endpoint name in source is a clue about intended behavior; it is not permission to call it and may be dead or environment-specific code.",
    example: "<button>Open project</button>\nIllustrative JavaScript: fetch('/api/projects/100')\nObservation: the UI can request project data\nNot established: who the server permits to read it",
    steps: [
      "Right-click a visible local button and choose Inspect. In Elements, identify its tag and visible label. Do not edit it; first learn what the browser rendered.",
      "Open Network and use the application normally. Match a click with any resulting request. Some clicks only change local display and send nothing.",
      "In Sources, search loaded files for a path you already observed. Use pretty-print if offered. Explain only the nearby behavior you can understand.",
      "Return to the Network request and inspect its Initiator information where available. This connects observed traffic to client code more reliably than guessing from a string search.",
      "Write a question about any unfamiliar code, with a short redacted excerpt. Do not paste AI-generated JavaScript into a logged-in Console simply to explore.",
    ],
    expected: "You can distinguish page structure, client behavior, and server response. You use code as context for observed traffic rather than treating hidden strings as findings.",
    troubleshoot: "Source maps may be absent, and bundled variable names may be meaningless. You can still investigate normal UI actions through Network. A hidden control or client-side role check does not establish a server-side bypass.",
    record: "Visible action, observed request, relevant source location if known, and one unanswered question. Preserve the distinction between actual traffic and unused code.",
    question: "If you unhide an Admin button in the DOM, have you become an administrator?",
    answer: "No. You changed your browser's presentation. The server must still authorize any request. A visible control is not evidence that an action succeeds.",
    aiPrompt: "Explain this small redacted HTML/JavaScript excerpt line by line for a non-programmer. Identify unknowns. Do not execute it or infer that a visible endpoint is authorized for testing.",
    sources: [],
  },
  {
    id: "beginner-18", title: "Inputs, reflection, and injection: learn the evidence boundary", minutes: 30,
    goal: "Recognize a follow-up question without confusing reflected text or an error with an exploit.",
    setup: "Paper exercise or an intentionally vulnerable training lesson you are authorized to use. The bundled project lab is not an XSS or SQL-injection lab.",
    concept: "Reflection means an application returns text you supplied. Injection means data is interpreted as part of a different language or operation, such as HTML/JavaScript, SQL, a command, or a template. XSS concerns script execution in a browser security context. An SQL error is not by itself proof that an attacker can control a database query. The context matters: text in a JSON string is not automatically executable HTML. Begin by understanding the input's normal route and output context, not by spraying payloads. These are different subjects requiring dedicated labs beyond a first traffic-reading course.",
    example: "Input: a harmless unique label, LEARN-ALPHA-01\nObserved output: {\"search\":\"LEARN-ALPHA-01\"}\nKnown: text was returned in JSON\nUnknown: whether any later page renders it unsafely\nNot demonstrated: script execution or database control",
    steps: [
      "On paper, label where the example value entered and where it appeared. Distinguish request input from response output.",
      "If practicing in a dedicated disposable lab, use an ordinary unique text marker in an allowed text field. Observe the response and rendered page without executable content.",
      "Record the output context: JSON string, HTML text, attribute, script, or unknown. Use DevTools Elements and Network to see that response text and rendered DOM can differ.",
      "Write what additional controlled lab evidence would be needed for the specific claim. If all you observed is reflection, call it reflection.",
      "Choose one official training topic for later depth instead of trying to test all injection classes at once. Do not apply unfamiliar payloads to GitLab merely because it runs locally with valuable data.",
    ],
    expected: "You can describe a data flow and explain why an input returning in a response is a lead, not a confirmed vulnerability.",
    troubleshoot: "If your marker is not present, the application may transform, omit, or return it later. Do not assume sanitization or safety without evidence. If an action stores content, remove only your own disposable test content afterward.",
    record: "Input location, benign marker, observed output context, whether data persisted, and exactly what was not demonstrated.",
    question: "A JSON response echoes your search text. Is that automatically XSS?",
    answer: "No. You must understand whether and how that data is later interpreted as executable browser content. Reflection alone does not establish execution or impact.",
    aiPrompt: "Help me classify this benign marker's input and output contexts. Explain reflection versus execution. Recommend conceptual prerequisites and an official isolated training lesson, not a payload list.",
    sources: [{ title: "PortSwigger Web Security Academy", url: "https://portswigger.net/web-security" }],
  },
  {
    id: "beginner-19", title: "Redirects and server fetches: who follows the URL?", minutes: 30,
    goal: "Distinguish a browser redirect from a server making an outbound request.",
    setup: "Use Burp history for the local /lab/redirect route; it points only to the fixed local project-100 route.",
    concept: "A redirect response tells the client where to go next, commonly through a Location header. A webhook or import-by-URL feature may instead cause the server to make a request itself. SSRF is a server-side request forgery problem: an attacker influences that server-side destination across an intended boundary. A URL-shaped input is only a clue. A browser visiting a URL is not evidence that the server fetched it. The bundled redirect is deliberately fixed and is not an open-redirect or SSRF vulnerability. GitLab's normal outbound-request protections are not failures to work around for beginner practice.",
    example: "GET /lab/redirect\n302 Location: /lab/projects/100\nThen the browser may send GET /lab/projects/100\nThat chain is client navigation, not proof of a server-side fetch.",
    steps: [
      "With Preserve log enabled in DevTools or Burp history recording, open http://127.0.0.1:5173/lab/redirect once.",
      "Find the redirect response and its Location, then the subsequent project request. The final address bar alone hides the intermediate response.",
      "Write which participant made the second request. Explain that a relative Location uses the existing origin here.",
      "For a hypothetical webhook field, draw browser → application server → destination. Label the final arrow 'not yet observed' unless you have actual authorized server-side evidence.",
      "Keep GitLab network restrictions enabled. Do not use cloud metadata addresses, internal networks, external callback services, or broad allow-list changes for this exercise.",
    ],
    expected: "You can reconstruct the two browser requests and avoid labeling them SSRF. You can explain what evidence is missing for a server-fetch claim.",
    troubleshoot: "If you see only 200, the browser may have followed the redirect before you inspected it. Preserve the log and inspect the earlier row. Any unexpected destination is a reason to stop and review scope.",
    record: "Original request, redirect status, Location, next observed request, participant making it, and the known scope boundary.",
    question: "Does a parameter named callbackUrl prove the server requests that URL?",
    answer: "No. It could be displayed, stored, validated, used by a browser, or ignored. Its name suggests a question; runtime evidence is needed to establish behavior.",
    aiPrompt: "Classify this redacted URL flow as browser navigation, possible server fetch, or unknown. Explain which evidence supports each arrow. Do not suggest internal addresses or changes that disable protective settings.",
    sources: [{ title: "PortSwigger: SSRF concepts", url: "https://portswigger.net/web-security/ssrf" }],
  },
  {
    id: "beginner-20", title: "Choose a useful question, not a pile of tests", minutes: 30,
    goal: "Prioritize one investigation and recognize when a topic needs a dedicated lab.",
    setup: "Your input inventory and notebook. This is a planning exercise with no network requests.",
    concept: "A useful lead combines an important asset, an expected rule, an observed input, and a safe way to test one uncertainty. An asset is something worth protecting, such as private project data. A trust boundary is where one party's data or authority should not be accepted blindly by another. Business-logic issues concern workflow rules such as who may approve a change; they are not identified by a special character alone. Uploads, rate limits, race conditions, CSRF, and injection each need specific background. Testing them blindly can alter data or disrupt a service. You can become independent by choosing small questions and documenting limits, not by memorizing a giant tool list.",
    example: "Lead: a project ID appears in a read request\nAsset: private project description\nRule: only approved members may read it\nUncertainty: does the server enforce membership?\nSmallest next step: establish visibility and test-account roles first",
    steps: [
      "List three observations from your captures. For each, write the possible asset and rule. Cross out claims that depend only on a scanner label or AI assertion.",
      "Choose the lead with the clearest local setup and least potential harm. Prefer a read-only owned object before workflows that send email, delete files, or spend money.",
      "List likely confounders and missing context. If the question requires concurrency or high request volume, defer it to a purpose-built training environment.",
      "Write the smallest next action that would reduce uncertainty. Sometimes that is reading documentation or confirming an account role, not sending a request.",
      "End with a stop rule and an honest success criterion: learning that a control works is a valid result.",
    ],
    expected: "One specific, defensible next question replaces a generic instruction to 'find bugs'. You can explain why other topics are postponed.",
    troubleshoot: "If you cannot identify a rule or meaningful consequence, the observation may be ordinary functionality. If you need a script you cannot explain, return to manual examples before automating.",
    record: "Lead, asset, rule, evidence, uncertainty, safest next action, expected result, and stopping condition. Keep deferred topics separate from confirmed observations.",
    question: "Is discovering that an access check correctly rejects your request a wasted session?",
    answer: "No. You learned normal behavior, improved your evidence discipline, and narrowed uncertainty. A useful investigation does not require inventing a vulnerability.",
    aiPrompt: "Rank these three local learning questions by clarity and safety, not potential severity. Explain missing prerequisites. Recommend one manual next step and what result would disprove my hypothesis.",
    sources: [],
  },
  {
    id: "beginner-21", title: "GitLab GDK: your optional realistic practice application", minutes: 40,
    goal: "Explain GDK, start and check it, and plan one normal GitLab workflow.",
    setup: "An existing GDK in Ubuntu. On this workstation its path is /home/superadmin/gdk; the Windows GDK folder holds notes only.",
    concept: "GitLab is a web application for repositories, projects, issues, memberships, and development workflows. The GitLab Development Kit runs a development instance with its supporting services. Its primary purpose is developing and testing GitLab itself. Your local instance can also provide realistic practice with accounts and projects you control; it is not intentionally vulnerable training software and no finding is guaranteed. GDK and SurfaceTrace are independent programs. You browse GitLab with DevTools or Burp, export an appropriate HAR, then import it into SurfaceTrace. Docker's 127.0.0.1 and Ubuntu's 127.0.0.1 are different network contexts, so direct active replay from the SurfaceTrace container is not automatically wired to GDK.",
    example: "Ubuntu terminal:\ncd ~/gdk\nbin/gdk start\nbin/gdk status\n\nWindows browser: http://127.0.0.1:3000/users/sign_in\nSurfaceTrace remains at http://127.0.0.1:5173\nStop GitLab only: cd ~/gdk && bin/gdk stop",
    steps: [
      "Open Ubuntu from the Start menu, not a PowerShell prompt inside the notes folder. Run cd ~/gdk, then bin/gdk start.",
      "Wait for startup, then check the GitLab sign-in URL in your Windows browser. A status table alone can be stale; a reachable page is an additional check.",
      "Use your locally configured account password. Do not assume an old default password or publish credentials in your notebook. Use an administrator only for setup, then a normal test account for observation.",
      "Create or choose a disposable project containing invented data. Confirm its visibility and each test account's membership through the GitLab UI; do not infer them from a username such as guest-tester.",
      "Browse one normal project page with DevTools or Burp. Capture and review only the relevant traffic, then import a sanitized capture into SurfaceTrace after preserving the previous import and notes.",
      "Keep this first GDK exercise passive. Do not change outbound-network policy, bulk-scan the instance, or update/reconfigure GDK while learning the normal workflow.",
    ],
    expected: "You understand what the target is and how recorded evidence reaches SurfaceTrace. Both apps can be used independently; neither is a plugin for the other.",
    troubleshoot: "Connection refused: verify both startup and an actual listener/page. A 502 during boot may mean Rails is not ready. bin/gdk doctor reports diagnostics; read findings before using corrective commands. Do not reset databases or run blanket updates to fix an unknown error.",
    record: "GDK path, browser URL, checked-out version, project visibility, verified roles, chosen normal action, and what was actually captured. Keep local environment findings separate from this portable lesson.",
    question: "Can you point SurfaceTrace's Docker replay at 127.0.0.1:3000 and assume it reaches Ubuntu's GitLab?",
    answer: "No. Loopback belongs to the process's own network environment. Use the passive HAR bridge first; active connectivity needs separate, carefully scoped configuration and verification.",
    aiPrompt: "Explain my GDK/Windows/Docker layout using only the paths and health results I provide. Separate confirmed checks from assumptions. Do not update, reset, truncate, expose ports, or change accounts without an explicit plan.",
    sources: [{ title: "GitLab: what GDK provides", url: "https://docs.gitlab.com/development/contributing/first_contribution/configure-dev-env-gdk/" }],
  },
  {
    id: "beginner-22", title: "Use AI as a tutor and reviewer", minutes: 25,
    goal: "Ask for useful help while retaining control of evidence and actions.",
    setup: "A small redacted exchange or synthetic example and your written question. No raw HAR upload is required.",
    concept: "AI is useful for explaining unfamiliar fields, checking a hypothesis, and reviewing notes. It can also invent endpoint behavior, confuse account policy, or give commands whose effects you do not understand. Separate observation from inference every time. A good prompt includes your goal, scope, known facts, missing evidence, and the kind of help you want. Ask for one manual step and its expected result. Before running a command, explain what it reads, writes, sends, and deletes. Redacted material should preserve structural relationships using labels like Account A, not actual tokens or private records.",
    example: "I am a beginner using my local lab only.\nFact: GET /lab/projects/100 returns Alpha; /200 returns Beta.\nQuestion: what can this comparison establish?\nHelp wanted: explain fields, challenge assumptions, ask one question.\nDo not send requests, scan, invent policy, or propose code yet.",
    steps: [
      "Write your own interpretation before asking AI. This gives you something to compare with its answer instead of automatically accepting it.",
      "Share the smallest redacted example that answers your question. Remove cookies, authorization values, private addresses, and personal data; keep field names and consistent synthetic labels.",
      "Ask AI to separate facts, hypotheses, and missing evidence. Require an alternative benign explanation and a result that would disprove the hypothesis.",
      "If it proposes a command or script, request a line-by-line explanation, expected output, state changes, and a no-network alternative. Do not paste it into a logged-in browser Console unexamined.",
      "Verify important claims against your capture and official documentation. Record where you disagreed or what remains uncertain.",
    ],
    expected: "You can use AI to learn without outsourcing permission, judgment, or the distinction between a guess and a finding.",
    troubleshoot: "If AI says 'definitely vulnerable' without a policy and reproducer, ask it to justify that statement. If it asks for a live secret, replace the value with a synthetic label. If you cannot explain a suggested action, do not run it yet.",
    record: "Your original interpretation, the question asked, useful explanation, checks performed, and unresolved assumptions. AI output is commentary, not primary evidence.",
    question: "What should you do when AI suggests a long scanning command you cannot explain?",
    answer: "Pause. Ask what every option does and what traffic or state changes it causes. Return to the smallest authorized manual observation; a confident recommendation is not sufficient justification.",
    aiPrompt: "Be my tutor, not an autonomous tester. Use plain language, ask me to predict the result, give one reversible step, and wait for my observation. Challenge unsupported conclusions and never ask me to share credentials.",
    sources: [],
  },
  {
    id: "beginner-23", title: "Write an evidence-backed report", minutes: 30,
    goal: "Produce a clear notebook entry another person can follow without your secrets.",
    setup: "One completed local comparison. A report may conclude expected behavior or unresolved uncertainty.",
    concept: "A useful report states the expected rule, the setup, the exact action, the observed result, and its meaning. Reproduction means someone can follow the same controlled steps; it does not mean publishing raw credentials. Impact is the actual consequence established by evidence, not the worst imaginable outcome. A title should describe behavior rather than announce a severity you have not justified. Keep captured facts, your annotations, AI commentary, and conclusions distinct. SurfaceTrace's ledger helps connect records; your explanation must still supply policy and context.",
    example: "Title: Local project-ID comparison returns two public records\nScope: owned synthetic lab; GET only\nExpected: 100→Alpha, 200→Beta\nSteps: capture baseline; change only path ID; compare\nObserved: three body fields changed; both 200\nConclusion: expected lab behavior; no access-control finding\nLimits: lab has no authentication",
    steps: [
      "Write a neutral title and one-sentence question. Add environment/version and the source of your permission or local ownership.",
      "Describe identities, object visibility, baseline, and the single change. Number the manual steps so a reviewer can repeat them with their own disposable setup.",
      "Include small redacted request/response excerpts and refer to your stored observations. Show meaningful body fields, not just status codes.",
      "Write expected versus actual behavior. State alternate explanations, missing evidence, and whether you reproduced the result. Do not claim a finding for the public toy lab.",
      "Before sharing, review screenshots, URLs, headers, bodies, and notes for secrets. Use the authorized reporting channel for real programs; keep practice notes private by default.",
    ],
    expected: "A reviewer understands what happened, why you tested it, and what you did not establish. A negative or inconclusive result is clearly labeled.",
    troubleshoot: "If the report only contains screenshots, add exact redacted steps. If it only contains a severity label, add the rule and demonstrated consequence. If reproducing would destroy data, return to a disposable setup and re-plan.",
    record: "Save the final report alongside capture references and a list of redactions. Do not overwrite your original private capture with a speculative AI rewrite.",
    question: "What makes '200 means critical IDOR' an inadequate report?",
    answer: "It lacks an established access rule, verified identities, protected content, controlled reproduction, and demonstrated consequence. The status alone does not justify the conclusion or severity.",
    aiPrompt: "Review my report as a skeptical maintainer. Identify missing reproduction details, unsupported impact claims, possible secrets, and alternative explanations. Preserve my evidence; do not invent results.",
    sources: [],
  },
  {
    id: "beginner-24", title: "Capstone: investigate with less help", minutes: 50,
    goal: "Complete the whole workflow and demonstrate what you understand before advancing.",
    setup: "The running local lab, a new disposable SurfaceTrace project, DevTools, Burp, and your notebook. GDK is optional after this capstone.",
    concept: "Independence is the ability to explain your target, choose a small question, gather the right evidence, and stop when the evidence runs out. You do not need to write code or discover a vulnerability to demonstrate those skills. In this capstone the answer is intentionally ordinary: changing the ID selects a different public record. Use AI only after making your own prediction and first interpretation. If you get stuck, return to the relevant lesson instead of adding more tools.",
    example: "Ready-to-advance checklist:\n[ ] I can state scope and stop conditions\n[ ] I can identify method, URL parts, inputs, status, and body\n[ ] I can capture and review a small HAR\n[ ] I can replay one safe local request and change one variable\n[ ] I can separate evidence from a hypothesis\n[ ] I can write an honest report without secrets",
    steps: [
      "Without looking at the answer, write the plan for comparing local project 100 with 200. Predict which fields will differ and why this does not test authentication.",
      "Capture the two browser exchanges in DevTools, export a sanitized HAR, and check its contents. Import into the learning installation after preserving any previous work and locate both observations.",
      "Use Burp's browser and Repeater to repeat the baseline once and change only the ID once. Confirm the destination before every Send.",
      "Create a passive SurfaceTrace comparison. Explain any other captured differences rather than assuming the selected mutation category proves they are absent.",
      "Write the report from lesson 23. Ask AI to critique it only after your own conclusion. Resolve or explicitly label each criticism using actual evidence.",
      "Explain the six checklist items aloud. Mark Practiced if you completed the exercise with notes; mark Comfortable only if you can repeat and explain it unaided. Choose one dedicated next lab rather than a broad live target.",
    ],
    expected: "Your report identifies Alpha/Beta and their field differences, preserves the public-lab limitation, and includes a reproducible capture/comparison workflow. You can recover from an empty Network list or a paused Burp request.",
    troubleshoot: "Stuck on capture: lesson 8. Confused about status or JSON: lessons 5 and 7. Burp won't load: lesson 12. Unsure whether it's a finding: lessons 11 and 16. Unable to connect to GDK: keep learning here; it is not required for this assessment.",
    record: "A completed report plus a personal list: what I did independently, where I needed help, and one next skill. Keep the scope of your claimed competence honest.",
    question: "When are you ready to move from this lab to another authorized environment?",
    answer: "When you can explain the workflow, protect evidence, verify identities, distinguish policy from assumptions, and follow that environment's explicit rules. This course is a foundation, not proof of expertise across every vulnerability class.",
    aiPrompt: "Assess my capstone by asking one question for each checklist item. Do not supply the answer until I try. Tell me which lesson to revisit and avoid recommending a real target before I can state its authorization and scope.",
    sources: [],
  },
];
